# Generated by Django 4.2.7 on 2026-01-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_savedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='youtube_recommendations',
            field=models.JSONField(default=dict, help_text='YouTube recommendations for missing skills'),
        ),
    ]
